### ISSUE TITLE
Usabilla(on Flutter) crash on Android 7

### ISSUE THREAD

**Issue by tjuros01** [usabilla/usabilla-u4a-flutter#17]
Hi, can you please check this error on Android 7

![image](https://user-images.githubusercontent.com/49923586/139158171-d2e07ca4-90f7-42a8-941d-7910201357af.png)
![image (1)](https://user-images.githubusercontent.com/49923586/139158186-587eb89a-3678-4ac8-95d3-dfb34d2d8fdd.png)
![image (2)](https://user-images.githubusercontent.com/49923586/139158194-7332057d-af73-4549-8b84-eb7703453aae.png)
![image (3)](https://user-images.githubusercontent.com/49923586/139158200-e5ec133c-6701-4a8b-9cb0-67028d2f3911.png)

**Comment by eduakaszas** [comment]
Hi @tjuros01,

Thank you for reaching out & we apologise for the delay on this.

Our SDK targets Java8 and uses components available from Android API 26, therefore if your app targets previous Android versions, you need to enable desugar support to have compatibility with Java 8. You can read more about this in [Google's guidelines. ](https://developer.android.com/studio/write/java8-support) and [this Flutter](https://docs.flutter.dev/development/add-to-app/android/project-setup) documentation might also help. 

Let us know if you have questions!

Kind regards, 
Édua

**Comment by kioli** [comment]
Hi @tjuros01
I'm not sure if you are still experiencing this issue, but given its stale status I'll close it.
Feel free to reopen it (or another one) if you experience other issues
