### ISSUE TITLE
Breaking Change in Dependency 'com.usabilla.sdk:ubform'

### ISSUE THREAD

**Issue by ovo-saxon-zerbino** [usabilla/usabilla-u4a-flutter#19]
Hi, 

This morning we noticed that some of our Flutter builds were failing in CI due to a build error that was not occuring last week despite no change to our dependency versioning. The error that we were presented was:

``` 
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
    is greater than this module's compileSdkVersion (android-30).
    Dependency: androidx.appcompat:appcompat:1.4.1.
    AAR metadata file: /home/circleci/.gradle/caches/transforms-2/files-2.1/32a80f0ada355cfa8b6c829cb57a7b80/appcompat-1.4.1/META-INF/com/android/build/gradle/aar-metadata.properties.
```

On investigation we identified that one of the dependencies of this package, `com.usabilla.sdk:ubform` has recently released v7.5.0 however, this release likely should have been marked as a major release as it includes an upgrade to it's own dependency, androidx.appcompat:appcompat from v1.3.1 to v1.4.1. This appears to have broken compatibility with android versions older than Android 12 (SDK 31)

As a workaround we have been able to specificy the version of this dependency in our app/build.gradle to the previous version by adding the following to our dependencies:

```
implementation('com.usabilla.sdk:ubform') {
    version {
        strictly '7.4.0'
    }
}
```

and also specify the following in our `android/gradle.properties`: `android.jetifier.blacklist=moshi-1.13.0.jar`

I would suggest it may be worthwhile you fixing to a specific version of this package or rolling back the change to `androidx.appcompat:appcompat`.

**Comment by ovo-saxon-zerbino** [comment]
As a follow on I've found that this actually isn't a valid workaround as it throws this error in a different pipeline

```
Execution failed for task ':flutter_usabilla:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/home/circleci/.gradle/caches/transforms-2/files-2.1/d1089d214528088cda729e158d8742fb/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found
```

**Comment by hiteshjain29** [comment]
Hi @ovo-saxon-zerbino ,

Thanks for letting us know. I will close this issue here for now but if the issue persists please feel free to reopen it again.

Many thanks,
Hitesh
