### ISSUE TITLE
v2.2.0 problem on IOS

### ISSUE THREAD

**Issue by fernandomiyahiradb1** [usabilla/usabilla-u4a-flutter#23]
Hello!
In the latest version 2.2.0, there is a problem when compiling for IOS where a variable is undefined.

![image](https://user-images.githubusercontent.com/94843571/187914022-0d92dbd8-61ce-4796-9c8a-2ab6eeb4f5ed.png)

**Comment by hiteshjain29** [comment]
Hi @fernandomiyahiradb1,

Thanks for letting us know. We have released a new version, so I will close this issue here for now but if the issue persists please feel free to reopen it again.

Many thanks,
Hitesh
